# Generated by Django 5.2.3 on 2025-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
