# Generated by Django 5.2.3 on 2025-07-30 11:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='youtubers',
            options={'ordering': ['name'], 'verbose_name_plural': 'YouTubers'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(default='game', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='blog.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(help_text='Game cover image', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_home',
            field=models.BooleanField(default=False, help_text='Display on homepage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, help_text='Game trailer or gameplay video', null=True, upload_to='blog/videos/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Review content', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(help_text='Rating from 0.0 to 5.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('creator', 'game')},
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_home'], name='blog_game_is_home_a28fda_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['category'], name='blog_game_categor_21b74c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['game', '-id'], name='blog_post_game_id_1fcfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['creator', '-id'], name='blog_post_creator_4fd85f_idx'),
        ),
    ]
