# Generated by Django 5.2.3 on 2025-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_timestamps'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
