# Generated by Django 5.2.3 on 2025-08-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_fix_constraints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtubers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
