# Generated by Django 5.2.3 on 2025-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_youtubers_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameplay_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='review_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tips_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='walkthrough_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
