# Generated by Django 5.2.3 on 2025-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_like_options_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metaScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
