# Generated by Django 5.2.3 on 2025-08-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_game_metascore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='walkthrough_video_id',
            new_name='trailer_video_id',
        ),
    ]
