# Generated by Django 5.2.3 on 2025-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_walkthrough_video_id_game_trailer_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(help_text='Game cover image', null=True, upload_to='blog/images/'),
        ),
    ]
