# Generated by Django 5.2.3 on 2025-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, help_text='Game cover image', null=True, upload_to='blog/images/'),
        ),
    ]
