# Generated by Django 5.2.3 on 2025-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='blog_game_categor_21b74c_idx',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
