# Generated by Django 5.2.3 on 2025-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_game_category_remove_genre_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.URLField(blank=True, help_text='RAWG API cover image URL', null=True),
        ),
    ]
