# Generated by Django 5.2.3 on 2025-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_home',
            field=models.BooleanField(default=True, help_text='Display on homepage'),
        ),
    ]
