# Generated by Django 5.2.3 on 2025-08-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_game_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
